main: net.wytrem.spigot.tictactoe.TicTacToe
name: TicTacToe
version: 1.4
author: wytrem
api-version: "1.14"
commands:
  tictactoe:
    description: Ask a player for a TicTacToe game
    usage: /tictactoe
    permission: tictactoe.use
permissions:
  tictactoe.use:
    description: Gives access to TicTacToe command
    default: true
